//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPaymentService.Business.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualPaymentService.Business.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;digitalWalletTokens&quot;:[{&quot;walletToken&quot;:&quot;ccca75ede7d-7723-4fa7-949b-df32baa21&quot;,&quot;walletTokenStatus&quot;:1,&quot;deviceType&quot;:&quot;MOBILE_PHONE&quot;,&quot;cardToken&quot;:&quot;123456-25a4d6a4-452b-4177-8192-d2312&quot;},{&quot;walletToken&quot;:&quot;ccc65eec8b4-3d7e-462b-9c3a-a36ce05d0&quot;,&quot;walletTokenStatus&quot;:1,&quot;deviceType&quot;:&quot;WATCH&quot;,&quot;cardToken&quot;:&quot;123456-25a4d6a4-452b-4177-8192-d2312&quot;},{&quot;walletToken&quot;:&quot;ccca77d91fe-8743-45ec-939b-95754c3be789&quot;,&quot;walletTokenStatus&quot;:2,&quot;deviceType&quot;:&quot;WATCH&quot;,&quot;cardToken&quot;:&quot;123456-25a4d6a4-452b-4177-8192-d2312&quot;},{&quot;walletToken&quot;:&quot;ccca77d91fe-874 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarqetaCardTokenTestData_ResponseWithFiveTokens_ExpectedMappedResult {
            get {
                return ResourceManager.GetString("MarqetaCardTokenTestData_ResponseWithFiveTokens_ExpectedMappedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;count&quot;: 9,
        ///    &quot;start_index&quot;: 0,
        ///    &quot;end_index&quot;: 0,
        ///    &quot;is_more&quot;: false,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;token&quot;: &quot;ccca75ede7d-7723-4fa7-949b-df32baa21&quot;,
        ///            &quot;card_token&quot;: &quot;123456-25a4d6a4-452b-4177-8192-d2312&quot;,
        ///            &quot;state&quot;: &quot;ACTIVE&quot;,
        ///            &quot;state_reason&quot;: &quot;Approved via automated validation&quot;,
        ///            &quot;fulfillment_status&quot;: &quot;PROVISIONED&quot;,
        ///            &quot;issuer_eligibility_decision&quot;: &quot;0000&quot;,
        ///            &quot;created_time&quot;: &quot;2021-10-01T18:55:45Z&quot;,
        ///            &quot;last [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarqetaCardTokenTestData_ResponseWithFiveTokens_SourceData {
            get {
                return ResourceManager.GetString("MarqetaCardTokenTestData_ResponseWithFiveTokens_SourceData", resourceCulture);
            }
        }
    }
}
