using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VirtualPaymentService.Model.Enums;

namespace VirtualPaymentService.Model.Responses
{
    /// <summary>
    /// Response contract for digital wallet token transition
    /// References:
    /// https://www.marqeta.com/docs/core-api/digital-wallets-management#_sample_response_body_3
    /// </summary>
    [ExcludeFromCodeCoverage]

    public class DigitalWalletTokenTransitionResponse
    {
        /// <summary>
        /// Transition Token generated by wallet provider for the related wallet transition request
        /// </summary>
        public string WalletTransitionToken { get; set; }

        /// <summary>
        /// State of the transition after processed by wallet provider.
        /// </summary>
        public DigitalWalletTokenStatus WalletTransitionState { get; set; }

        /// <summary>
        /// Type of transition after processing, as defined by wallet provider.
        /// </summary>
        public string WalletTransitionType { get; set; }

        /// <summary>
        /// The digital wallet token’s provisioning fulfillment status after receiving transition response.
        /// </summary>
        /// <remarks>
        /// Expected Values: DECISION_RED, DECISION_YELLOW, DECISION_GREEN, REJECTED, PROVISIONED
        /// </remarks>
        public string FulfillmentStatus { get; set; }
    }
}
